### PR TITLE
Unity5

### PR DESCRIPTION
**Pull request by ZakCollins**
I'm thinking that we should switch to the new version of Unity since it has some features that will definitely be useful and I haven't encountered any problems in switching to it so far. This PR includes the conversion to Unity5 and 1 bug fix. You can download Unity 5.0 here:

http://unity3d.com/get-unity/download?ref=personal

### CODE REVIEW

**Comment by thejinxters** [comment]
When I opened the proejct a few files required updating. I wonder if this is a mac compatibility thing. Regardless, they were minor file updates (using GetComponent instead of making direct references)

Here is a list of the files:
```
	modified:   Assets/9 Other/Pathfinding/Scenes/Scripts/JSGridPlayer.js
	modified:   Assets/9 Other/Pathfinding/Scenes/Scripts/JSGridPlayer2D.js
	modified:   Assets/9 Other/Pathfinding/Scenes/Scripts/SetGrid.cs
	modified:   Assets/9 Other/Pathfinding/Scenes/Scripts/TDManager.cs
	modified:   Assets/9 Other/Pathfinding/Scripts/DynamicMapUpdate.cs
	modified:   Assets/9 Other/Pathfinding/Scripts/DynamicTDGridObject.cs
	modified:   Assets/9 Other/Pathfinding/Scripts/WaypointNode.cs
	modified:   Assets/9 Other/RAIN/Editor/RAINProjectState.asset
	modified:   Assets/9 Other/RAIN/Editor/RAINSettings.asset
```

I can push them up as everything appeared to still work!

**Comment by thejinxters** [comment]
good call on removing rain

**Comment by ZakCollins** [comment]
I tried removing it before but it didn't take. Hopefully it will stay removed this time.

**Comment by thejinxters** [comment]
maybe you forgot the --all tag for commiting deleted files?

**Comment by ZakCollins** [comment]
Ya, I didn't do "git add -A" last time but I did this time so hopefully it will work. This is also why you needed to update the pathfinding and RAIN scripts when you opened the project. Those were deleted on my computer when it updated for me.

**Comment by thejinxters** [comment]
Yep that would do it! Glad we got it all worked out.

**Pull request merged**
